name: Build on Windows with MSYS2

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DRUMSTICK: DrumstickV2
  SONIVOX: SonivoxV4

jobs:
  build:
    runs-on: windows-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            # { icon: 'â¬›', sys: mingw32 } # There are no 32 bit packages for Qt6 in msys2 anymore
            - { icon: 'ðŸŸ¦', sys: mingw64 }
            - { icon: 'ðŸŸ¨', sys: ucrt64  }
            - { icon: 'ðŸŸ§', sys: clang64 }
    name: ðŸš§${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{matrix.sys}}
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p
          qt6-tools:p
          qt6-translations:p
          qt6-multimedia:p

    - name: '${{ matrix.icon }} Checkout'
      uses: actions/checkout@v4

    - name: '${{ matrix.icon }} Download Sonivox'
      uses: dawidd6/action-download-artifact@v3
      with:
        name: ${{env.SONIVOX}}-msys2-${{matrix.sys}}
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/sonivox
        allow_forks: false
        workflow: cmake-win.yml

    - name: '${{ matrix.icon }} Extract Sonivox'
      run: tar xvf ${{env.SONIVOX}}.tar

    - name: '${{ matrix.icon }} Download Drumstick'
      uses: dawidd6/action-download-artifact@v3
      with:
        name: ${{env.DRUMSTICK}}-${{matrix.sys}}
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        allow_forks: false
        workflow: cmake-win.yml

    - name: '${{ matrix.icon }} Extract Drumstick'
      run: tar xvf ${{env.DRUMSTICK}}.tar

    - name: '${{ matrix.icon }} Configure CMake'
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK}};${{env.SONIVOX}}"

    - name: '${{ matrix.icon }} Build'
      run: cmake --build build --config ${{env.BUILD_TYPE}}
